# -*- coding: utf-8 -*-
"""28_07_25_update_merged_file_by_Rana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X6tuA9wjUyOYc9nyu7oI_IPzQTfbP1N
"""

# -*- coding: utf-8 -*-
"""Comprehensive Gene Expression Batch Correction Pipeline"""
# === Step 0: Install Required Packages ===
!pip install -q combat pandas numpy matplotlib seaborn scikit-learn scipy

# === Step 1: Import Libraries and Setup ===
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from combat.pycombat import pycombat
from scipy.stats import skew
from matplotlib.patches import Ellipse
from google.colab import files
import shutil
import warnings

# Suppress warnings
warnings.filterwarnings('ignore')

# Configure plotting
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
plt.rcParams.update({
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'font.family': 'sans-serif'
})
COLORS = sns.color_palette("Set2", 10)

# === Step 2: Upload and Load Data ===
print("="*60)
print("📁 GENE EXPRESSION DATA UPLOAD")
print("="*60)

uploaded = files.upload()
if not uploaded:
    raise ValueError("❌ No files uploaded!")

data_frames = []
batch_labels = []
dataset_names = list(uploaded.keys())

for idx, fname in enumerate(dataset_names):
    print(f"\n📊 Processing: {fname}")
    try:
        df = pd.read_csv(fname, index_col=0)
        print(f"   Original: {df.shape[0]} genes × {df.shape[1]} samples")

        # Handle duplicates
        if df.index.duplicated().any():
            df = df.groupby(df.index).mean()
            print(f"   Deduplicated: {df.shape[0]} genes")

        # Validate numeric data
        non_numeric = df.select_dtypes(exclude=np.number).columns
        if non_numeric.any():
            df = df.select_dtypes(include=np.number)
            print(f"   Removed {len(non_numeric)} non-numeric columns")

        data_frames.append(df)
        batch_labels += [idx] * df.shape[1]
        print(f"✅ Loaded: {df.shape[0]} genes × {df.shape[1]} samples")

    except Exception as e:
        print(f"❌ Error: {str(e)}")
        continue

if not data_frames:
    raise ValueError("❌ No valid datasets loaded!")

# === Step 3: Create Output Directory ===
output_dir = 'batch_correction_results'
os.makedirs(f"{output_dir}/plots", exist_ok=True)
os.makedirs(f"{output_dir}/data", exist_ok=True)
print(f"📁 Output directory: {output_dir}")

# === Step 4: Individual Dataset Visualization ===
print("\n" + "="*60)
print("📊 DATASET VISUALIZATION")
print("="*60)

for i, df in enumerate(data_frames):
    plt.figure(figsize=(10, 4))
    sns.boxplot(data=df, showfliers=False, palette="coolwarm")
    plt.title(f'{dataset_names[i]} - Raw Expression\nn={df.shape[1]} samples', fontweight='bold')
    plt.xticks([])
    plt.ylabel("Expression")
    plt.tight_layout()
    safe_name = dataset_names[i].replace(" ", "_").replace(".csv", "")
    plt.savefig(f"{output_dir}/plots/raw_{safe_name}.png")
    plt.show()

# === Step 5: Merge by Common Genes ===
common_genes = set.intersection(*[set(df.index) for df in data_frames])
print(f"\n🧬 Common genes: {len(common_genes)}")

merged = pd.concat(data_frames, axis=1, join='inner')
print(f"✅ Merged data: {merged.shape[0]} genes × {merged.shape[1]} samples")

# === Step 6: Merged Data Visualization ===
plt.figure(figsize=(12, 6))
sns.boxplot(data=merged, showfliers=False, palette="crest")
plt.title("Merged Raw Expression", fontweight='bold')
plt.xticks([])
plt.ylabel("Expression")

# Add batch separators
sample_idx = 0
batch_counts = [df.shape[1] for df in data_frames]
for i in range(len(batch_counts)-1):
    sample_idx += batch_counts[i]
    plt.axvline(x=sample_idx-0.5, color='red', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig(f"{output_dir}/plots/merged_raw.png")
plt.show()

# === Step 7: Transformation Assessment ===
print("\n" + "="*60)
print("🔬 TRANSFORMATION ASSESSMENT")
print("="*60)

# Calculate key metrics
merged_numeric = merged.select_dtypes(include=np.number)
skewness = merged_numeric.apply(skew, axis=1).mean()
cv = (merged_numeric.std(axis=1) / merged_numeric.mean(axis=1)).mean()
zero_count = (merged_numeric == 0).sum().sum()

print(f"📊 Mean skewness: {skewness:.2f}")
print(f"📊 Mean CV: {cv:.2f}")
print(f"📊 Zero values: {zero_count}")

# Visual assessment
fig, ax = plt.subplots(1, 2, figsize=(12, 4))
sns.histplot(merged_numeric.values.flatten(), bins=50, kde=True, ax=ax[0])
ax[0].set_title('Value Distribution', fontweight='bold')

sns.histplot(np.log2(merged_numeric + 1).values.flatten(), bins=50, kde=True, ax=ax[1], color='salmon')
ax[1].set_title('Log2(x+1) Preview', fontweight='bold')

plt.tight_layout()
plt.savefig(f"{output_dir}/plots/transformation_assessment.png")
plt.show()

# === Step 8: Interactive Transformation Decision ===
print("\n" + "="*60)
print("🤖 TRANSFORMATION DECISION")
print("="*60)
print("1. Apply Log2 transformation (recommended)")
print("2. Apply Log10 transformation")
print("3. Skip transformation")

choice = input("Enter choice (1-3): ").strip()
transform_type = None

if choice == '1':
    transform_type = 'log2'
    print("✅ Selected: Log2 transformation")
elif choice == '2':
    transform_type = 'log10'
    print("✅ Selected: Log10 transformation")
else:
    print("✅ Selected: No transformation")

# === Step 9: Apply Transformation & Clean Data ===
print("\n" + "="*60)
print("🔧 DATA TRANSFORMATION")
print("="*60)

if transform_type:
    # Apply transformation
    pseudo_count = 1 if zero_count > 0 else 0
    if transform_type == 'log2':
        transformed = np.log2(merged_numeric + pseudo_count)
    else:
        transformed = np.log10(merged_numeric + pseudo_count)

    print(f"Applied {transform_type} with pseudo-count={pseudo_count}")
else:
    transformed = merged_numeric.copy()
    print("Using raw data without transformation")

# Clean data
print("\n🧹 Cleaning data...")
print(f"Before: {transformed.shape[0]} genes × {transformed.shape[1]} samples")

# Remove problematic values
cleaned = transformed.replace([np.inf, -np.inf], np.nan).dropna()
cleaned = cleaned.loc[cleaned.var(axis=1) > 1e-10]  # Remove low-variance genes

print(f"After: {cleaned.shape[0]} genes × {cleaned.shape[1]} samples")
print(f"Removed: {transformed.shape[0] - cleaned.shape[0]} genes")

# Save cleaned data
cleaned_file_path = f"{output_dir}/data/log_tranformed_cleaned_data.csv"
cleaned.to_csv(cleaned_file_path)
print(f"💾 Saved cleaned data: {cleaned_file_path}")

# Download the cleaned data file
try:
    from google.colab import files
    files.download(cleaned_file_path)
    print(f"✅ Downloaded: {cleaned_file_path}")
except ImportError:
    print("⚠️ Not in Google Colab - file saved locally")
except Exception as e:
    print(f"⚠️ Download failed: {str(e)}")

# === Step 10: Batch Correction ===
print("\n" + "="*60)
print("🔄 BATCH CORRECTION")
print("="*60)

# Adjust batch labels
adjusted_batch_labels = batch_labels[:cleaned.shape[1]]

print("Applying ComBat correction...")
try:
    corrected = pycombat(cleaned, adjusted_batch_labels)
    print("✅ Batch correction successful!")
except Exception as e:
    print(f"❌ Combat failed: {str(e)}")
    print("⚠️ Using original data instead")
    corrected = cleaned.copy()

# Visual comparison
plt.figure(figsize=(14, 6))

plt.subplot(121)
sns.boxplot(data=cleaned, showfliers=False, palette="coolwarm")
plt.title("Before Correction", fontweight='bold')
plt.xticks([])

plt.subplot(122)
sns.boxplot(data=corrected, showfliers=False, palette="viridis")
plt.title("After Correction", fontweight='bold')
plt.xticks([])

plt.tight_layout()
plt.savefig(f"{output_dir}/plots/before_after_correction.png")
plt.show()

# === Step 11: Quality Assessment ===
print("\n" + "="*60)
print("📈 QUALITY ASSESSMENT")
print("="*60)

def plot_pca(data, labels, title, filename):
    pca = PCA(n_components=2)
    scaled = StandardScaler().fit_transform(data.T)
    pcs = pca.fit_transform(scaled)

    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=pcs[:,0], y=pcs[:,1], hue=labels, palette="Set2", s=80)
    plt.title(f"{title}\nVariance: PC1={pca.explained_variance_ratio_[0]*100:.1f}%, PC2={pca.explained_variance_ratio_[1]*100:.1f}%")
    plt.xlabel("PC1")
    plt.ylabel("PC2")
    plt.tight_layout()
    plt.savefig(filename)
    plt.show()

# PCA before correction
plot_pca(cleaned, adjusted_batch_labels,
         "PCA - Before Correction",
         f"{output_dir}/plots/pca_before.png")

# PCA after correction
plot_pca(corrected, adjusted_batch_labels,
         "PCA - After Correction",
         f"{output_dir}/plots/pca_after.png")

# === Step 12: Save Results ===
print("\n" + "="*60)
print("💾 SAVING RESULTS")
print("="*60)

# Save corrected data
corrected_df = pd.DataFrame(
    corrected,
    index=cleaned.index,
    columns=cleaned.columns
)
corrected_df.to_csv(f"{output_dir}/data/batch_corrected_final_merged_file.csv")
print(f"✅ Corrected data saved: {output_dir}/data/batch_corrected_final_merged_file.csv")

# Create zip archive
shutil.make_archive(output_dir, 'zip', output_dir)
print(f"📦 Created results archive: {output_dir}.zip")

# === Step 13: Download Results ===
print("\n" + "="*60)
print("📥 DOWNLOADING RESULTS")
print("="*60)
files.download(f"{output_dir}.zip")
print("✅ Download complete! Your analysis is ready.")